language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# Install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: nosetests -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
